org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.114

mod_id=thaumaturgeadditions
mod_name=Thaumaturge Additions
mod_license=LGPL-3.0
mod_version=0.0.1
mod_group_id=com.blackmooss.thaumaturgeaddon
mod_authors=Black_Moss
mod_description=Add more content for Thaumaturge.

## 26.1.2-NeoForge-1.0.2
thaumaturge_version=9095192
lithostitched_version=1.8.0-neoforge-26.1
jei_version=29.6.2.31
curios_version=15.0.0+26.1.2
jade_version=26.1.11+neoforge
## 26.1.2-11.2.8
travelersbackpack_version=glTGAXmg
sophisticatedcore_version=26.1.2-1.5.6.2372
sophisticatedbackpacks_version=26.1.2-3.26.9.2186
