license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "logo.png"
authors = "${mod_authors}"
description = "${mod_description}"

[[mixins]]
config = "${mod_id}.mixins.json"


[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "thaumaturge"
type = "required"
versionRange = "[1.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "jei"
type = "optional"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "travelersbackpack"
type = "optional"
versionRange = "[11.2.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "sophisticatedbackpacks"
type = "optional"
versionRange = "[3.26.9,)"
ordering = "AFTER"
side = "BOTH"
